name: FJ Bot Runner


concurrency:
  group: fj-bot-production
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Deps & Chrome
        run: |
          sudo apt-get update
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb xvfb

      - name: Install Python Libs
        run: |
          pip install --upgrade pip
          pip install seleniumbase pyvirtualdisplay colorama nest_asyncio requests pytz

      - name: Install Driver
        run: |
          seleniumbase install chromedriver

      - name: Run Bot
        env: 
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          FJ_URL: ${{ secrets.FJ_URL }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" python main.py
